/* Generated by re2c 0.12.1 on Sat Dec  1 13:57:40 2007 */
#line 1 "tokenizer.re"
/*
 * Copyright (C) 2006 Cooper Street Innovations Inc.
 *	Charles Eidsness    <charles@cooper-street.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 *
 */

#include <math.h>
#include <log.h>
#include <data.h>
#include <ctype.h>

#include "tokenizer.h"
#include "parser.h"

/* RE Format parser defines */
#define	YYCTYPE		char
#define	YYCURSOR	cursor
#define	YYMARKER	marker

#line 37 "tokenizer.re"


#line 52 "tokenizer.re"


static token_ * tokenNew(int type, double **variable, double constant,
		double *minDiv)
{
	token_ *r;
	r = malloc(sizeof(token_));
	ReturnNULLIf(r == NULL, "Malloc Failed");
	r->type = type;
	r->variable = variable;
	r->constant = constant;
	r->minDiv = minDiv;
	return r;
}


int tokenSolve(token_ *r, tokenSolveArgs_ *args)
{
	ReturnErrIf(r == NULL);
	ReturnErrIf(args == NULL);

	if(args->diffVariable != NULL) {
		if((r->type == TOKEN_VARIABLE) &&
				(*(r->variable) == *(args->diffVariable))) {
			Debug("%s", ParseTokenName(TOKEN_DIFF_VARIABLE));
			Parse(args->parser, TOKEN_DIFF_VARIABLE, r, args->solution);
			ReturnErrIf(isnan(*args->solution), "Parser failed");
			return 0;
		}
	}

	Debug("%s", ParseTokenName(r->type));
	Parse(args->parser, r->type, r, args->solution);
	ReturnErrIf(isnan(*args->solution), "Parser failed");
	return 0;
}

int tokenDestroy(token_ *r)
{
	if(r != NULL) {
		free(r);
	}
	return 0;
}

#define Attach(tok, var, con, minDiv) \
	GotoFailedIf(listAdd(tokens, tokenNew(tok, var, con, minDiv), NULL))

list_ * tokenizerNew(char *buffer, tokenizerGetVarPtr getVarFunc,
		void *private, double *minDiv)
{
	list_ *tokens = NULL;
	char *cursor = NULL, *marker = NULL, *start = NULL, *tmp, *comma, *lparen;
	double **variable;
	int i, c;

	ReturnNULLIf(buffer == NULL);
	ReturnNULLIf(getVarFunc == NULL);

	Debug("Creating tokenizer");
	tokens = listNew(tokens);
	ReturnNULLIf(tokens == NULL);
	cursor = buffer;
	marker = buffer;

parse:
	start = cursor;
{
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0, 128,  64,   0,   0,  64,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		128,   0,   0,  40,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		 24,  24,  24,  24,  24,  24,  24,  24,
		 24,  24,  40,   0,   0,   0,   0,   0,
		 40,  40,  40,  40,  40,  40,  40,  40,
		 40,  40,  40,  40,  40,  40,  40,  40,
		 40,  40,  40,  40,  40,  40,  40,  40,
		 40,  40,  40,   0,   0,   0,   0,  40,
		  0,  40,  40,  40,  40,  40,  40,  40,
		 40,  40,  40,  40,  40,  40,  40,  40,
		 40,  40,  40,  40,  40,  40,  40,  40,
		 40,  40,  40,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
	};

#line 145 "tokenizer.c"
	{
		YYCTYPE yych;
		unsigned int yyaccept = 0;

		yych = *YYCURSOR;
		switch(yych) {
		case 0x00:	goto yy6;
		case 0x09:
		case ' ':	goto yy2;
		case 0x0A:
		case 0x0D:	goto yy4;
		case '!':	goto yy37;
		case '#':
		case ':':
		case '@':
		case 'B':
		case 'D':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'b':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy47;
		case '&':	goto yy39;
		case '(':	goto yy27;
		case ')':	goto yy29;
		case '*':	goto yy21;
		case '+':	goto yy17;
		case '-':	goto yy19;
		case '.':	goto yy45;
		case '/':	goto yy23;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy43;
		case '<':	goto yy33;
		case '=':	goto yy35;
		case '>':	goto yy31;
		case 'A':
		case 'a':	goto yy8;
		case 'C':
		case 'c':	goto yy10;
		case 'E':
		case 'e':	goto yy11;
		case 'I':
		case 'i':	goto yy16;
		case 'L':
		case 'l':	goto yy12;
		case 'S':
		case 's':	goto yy13;
		case 'T':
		case 't':	goto yy14;
		case 'U':
		case 'u':	goto yy15;
		case 'V':
		case 'v':	goto yy46;
		case '^':	goto yy25;
		case '|':	goto yy41;
		default:	goto yy48;
		}
yy2:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy188;
yy3:
#line 120 "tokenizer.re"
		{ goto parse; }
#line 246 "tokenizer.c"
yy4:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if(yybm[0+yych] & 64) {
			goto yy185;
		}
		if(yych == '+') goto yy184;
yy5:
#line 241 "tokenizer.re"
		{ Error("Unexpected character %s", cursor-1);	goto failed; }
#line 257 "tokenizer.c"
yy6:
		++YYCURSOR;
#line 121 "tokenizer.re"
		{ Attach(0, NULL, 0, NULL);						goto passed; }
#line 262 "tokenizer.c"
yy8:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= 'T') {
			if(yych <= 'C') {
				if(yych <= 'A') goto yy50;
				if(yych <= 'B') goto yy156;
				goto yy157;
			} else {
				if(yych <= 'R') goto yy50;
				if(yych <= 'S') goto yy158;
				goto yy159;
			}
		} else {
			if(yych <= 'c') {
				if(yych <= 'a') goto yy50;
				if(yych <= 'b') goto yy156;
				goto yy157;
			} else {
				if(yych <= 'r') goto yy50;
				if(yych <= 's') goto yy158;
				if(yych <= 't') goto yy159;
				goto yy50;
			}
		}
yy9:
#line 230 "tokenizer.re"
		{
		tmp = malloc(cursor - start + 1);
		GotoFailedIf(tmp == NULL);
		/* NOTE: tmp is freed by the function it's passed to */
		strncpy(tmp, start, (cursor - start));
		tmp[cursor - start] = 0x0;
		variable = getVarFunc(tmp, private);
		GotoFailedIf(variable == NULL);
		Attach(TOKEN_VARIABLE, variable, 0, NULL);
		goto parse;
	}
#line 300 "tokenizer.c"
yy10:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy149;
		if(yych == 'o') goto yy149;
		goto yy50;
yy11:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy145;
		if(yych == 'x') goto yy145;
		goto yy50;
yy12:
		yych = *++YYCURSOR;
		if(yych <= 'O') {
			if(yych <= 'M') goto yy50;
			if(yych <= 'N') goto yy138;
			goto yy139;
		} else {
			if(yych <= 'm') goto yy50;
			if(yych <= 'n') goto yy138;
			if(yych <= 'o') goto yy139;
			goto yy50;
		}
yy13:
		yych = *++YYCURSOR;
		if(yych <= 'Q') {
			if(yych == 'I') goto yy126;
			if(yych <= 'P') goto yy50;
			goto yy127;
		} else {
			if(yych <= 'i') {
				if(yych <= 'h') goto yy50;
				goto yy126;
			} else {
				if(yych == 'q') goto yy127;
				goto yy50;
			}
		}
yy14:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy122;
		if(yych == 'a') goto yy122;
		goto yy50;
yy15:
		yych = *++YYCURSOR;
		if(yych <= 'Q') {
			if(yych == '(') goto yy115;
			goto yy50;
		} else {
			if(yych <= 'R') goto yy114;
			if(yych == 'r') goto yy114;
			goto yy50;
		}
yy16:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if(yych <= 'E') {
			if(yych == '(') goto yy109;
			goto yy50;
		} else {
			if(yych <= 'F') goto yy108;
			if(yych == 'f') goto yy108;
			goto yy50;
		}
yy17:
		++YYCURSOR;
#line 141 "tokenizer.re"
		{ Attach(TOKEN_PLUS, NULL, 0, minDiv);		goto parse; }
#line 368 "tokenizer.c"
yy19:
		++YYCURSOR;
#line 142 "tokenizer.re"
		{ Attach(TOKEN_MINUS, NULL, 0, minDiv);	goto parse; }
#line 373 "tokenizer.c"
yy21:
		++YYCURSOR;
#line 143 "tokenizer.re"
		{ Attach(TOKEN_TIMES, NULL, 0, minDiv);	goto parse; }
#line 378 "tokenizer.c"
yy23:
		++YYCURSOR;
#line 144 "tokenizer.re"
		{ Attach(TOKEN_DIVIDE, NULL, 0, minDiv);	goto parse; }
#line 383 "tokenizer.c"
yy25:
		++YYCURSOR;
#line 145 "tokenizer.re"
		{ Attach(TOKEN_POWER, NULL, 0, minDiv);	goto parse; }
#line 388 "tokenizer.c"
yy27:
		++YYCURSOR;
#line 146 "tokenizer.re"
		{ Attach(TOKEN_LPAREN, NULL, 0, NULL);		goto parse; }
#line 393 "tokenizer.c"
yy29:
		++YYCURSOR;
#line 147 "tokenizer.re"
		{ Attach(TOKEN_RPAREN, NULL, 0, NULL);		goto parse; }
#line 398 "tokenizer.c"
yy31:
		++YYCURSOR;
#line 148 "tokenizer.re"
		{ Attach(TOKEN_GREATERTHAN, NULL, 0, NULL);		goto parse; }
#line 403 "tokenizer.c"
yy33:
		++YYCURSOR;
#line 149 "tokenizer.re"
		{ Attach(TOKEN_LESSTHAN, NULL, 0, NULL);		goto parse; }
#line 408 "tokenizer.c"
yy35:
		++YYCURSOR;
#line 150 "tokenizer.re"
		{ Attach(TOKEN_EQUAL, NULL, 0, NULL);			goto parse; }
#line 413 "tokenizer.c"
yy37:
		++YYCURSOR;
#line 151 "tokenizer.re"
		{ Attach(TOKEN_NOT, NULL, 0, NULL);			goto parse; }
#line 418 "tokenizer.c"
yy39:
		++YYCURSOR;
#line 152 "tokenizer.re"
		{ Attach(TOKEN_AND, NULL, 0, NULL);		goto parse; }
#line 423 "tokenizer.c"
yy41:
		++YYCURSOR;
#line 153 "tokenizer.re"
		{ Attach(TOKEN_OR, NULL, 0, NULL);		goto parse; }
#line 428 "tokenizer.c"
yy43:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		switch(yych) {
		case '.':	goto yy103;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy104;
		case 'E':
		case 'e':	goto yy64;
		case 'F':
		case 'f':	goto yy83;
		case 'G':
		case 'g':	goto yy68;
		case 'K':
		case 'k':	goto yy71;
		case 'M':
		case 'm':	goto yy86;
		case 'N':
		case 'n':	goto yy77;
		case 'P':
		case 'p':	goto yy80;
		case 'T':
		case 't':	goto yy65;
		case 'U':
		case 'u':	goto yy74;
		default:	goto yy89;
		}
yy44:
#line 164 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start), NULL); goto parse; }
#line 467 "tokenizer.c"
yy45:
		yych = *++YYCURSOR;
		if(yybm[0+yych] & 16) {
			goto yy62;
		}
		goto yy5;
yy46:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if(yych == '(') goto yy51;
		goto yy50;
yy47:
		yych = *++YYCURSOR;
		goto yy50;
yy48:
		yych = *++YYCURSOR;
		goto yy5;
yy49:
		++YYCURSOR;
		yych = *YYCURSOR;
yy50:
		if(yybm[0+yych] & 8) {
			goto yy49;
		}
		goto yy9;
yy51:
		yych = *++YYCURSOR;
		if(yych == ')') goto yy52;
		if(yych != ',') goto yy54;
yy52:
		YYCURSOR = YYMARKER;
		if(yyaccept <= 1) {
			if(yyaccept <= 0) {
				goto yy5;
			} else {
				goto yy9;
			}
		} else {
			goto yy44;
		}
yy53:
		++YYCURSOR;
		yych = *YYCURSOR;
yy54:
		if(yych <= '/') {
			if(yych <= '(') {
				if(yych == '#') goto yy53;
				goto yy52;
			} else {
				if(yych <= ')') goto yy55;
				if(yych == ',') goto yy57;
				goto yy52;
			}
		} else {
			if(yych <= '^') {
				if(yych <= ':') goto yy53;
				if(yych <= '?') goto yy52;
				if(yych <= 'Z') goto yy53;
				goto yy52;
			} else {
				if(yych == '`') goto yy52;
				if(yych <= 'z') goto yy53;
				goto yy52;
			}
		}
yy55:
		++YYCURSOR;
#line 213 "tokenizer.re"
		{
		tmp = malloc(cursor - start + 1);
		GotoFailedIf(tmp == NULL);
		/* NOTE: tmp is freed by the function it's passed to */
		strncpy(tmp, start, (cursor - start));
		/* change function name to lower case */
		for(i = 0; tmp[i] != '('; i++) {
			c = tolower(tmp[i]);
			GotoFailedIf(c == EOF);
			tmp[i] = c;
		}
		tmp[cursor - start] = 0x0;
		variable = getVarFunc(tmp, private);
		GotoFailedIf(variable == NULL);
		Attach(TOKEN_VARIABLE, variable, 0, NULL);
		goto parse;
	}
#line 553 "tokenizer.c"
yy57:
		yych = *++YYCURSOR;
		if(yych == ')') goto yy52;
		goto yy59;
yy58:
		++YYCURSOR;
		yych = *YYCURSOR;
yy59:
		if(yych <= ':') {
			if(yych <= '(') {
				if(yych == '#') goto yy58;
				goto yy52;
			} else {
				if(yych <= ')') goto yy60;
				if(yych <= '/') goto yy52;
				goto yy58;
			}
		} else {
			if(yych <= '^') {
				if(yych <= '?') goto yy52;
				if(yych <= 'Z') goto yy58;
				goto yy52;
			} else {
				if(yych == '`') goto yy52;
				if(yych <= 'z') goto yy58;
				goto yy52;
			}
		}
yy60:
		++YYCURSOR;
#line 165 "tokenizer.re"
		{
		/* TODO: This is a little inefficient, could clean it up someday, use
			re2c, there's no reason to go over this twice... but then the
			performance hit is so small who cares? */
		for(lparen = start; *lparen != '('; lparen++);
		for(comma = lparen; *comma != ','; comma++);

		/* First get left variable */
		tmp = malloc(comma - start + 2);
		GotoFailedIf(tmp == NULL);
		strncpy(tmp, start, (comma - start));
		/* change function name to lower case */
		for(i = 0; tmp[i] != '('; i++) {
			c = tolower(tmp[i]);
			GotoFailedIf(c == EOF);
			tmp[i] = c;
		}
		tmp[comma - start] = ')';
		tmp[comma - start + 1] = 0x0;
		variable = getVarFunc(tmp, private);
		GotoFailedIf(variable == NULL);
		Attach(TOKEN_LPAREN, NULL, 0, NULL)
		Attach(TOKEN_VARIABLE, variable, 0, NULL);

		/* Minus */
		Attach(TOKEN_MINUS, NULL, 0, minDiv);

		/* the right variable */
		tmp = malloc((lparen - start) + (cursor - comma) + 2);
		GotoFailedIf(tmp == NULL);
		/* NOTE: tmp is freed by the function it's passed to */
		strncpy(tmp, start, (lparen - start + 1));
		Debug("%s", tmp);
		strncpy(&tmp[(lparen - start)+1], comma+1, (cursor - comma));
		Debug("%s", tmp);
		/* change function name to lower case */
		for(i = 0; tmp[i] != '('; i++) {
			c = tolower(tmp[i]);
			GotoFailedIf(c == EOF);
			tmp[i] = c;
		}
		tmp[lparen - start + cursor - comma] = 0x0;
		variable = getVarFunc(tmp, private);
		GotoFailedIf(variable == NULL);
		Attach(TOKEN_VARIABLE, variable, 0, NULL);
		Attach(TOKEN_RPAREN, NULL, 0, NULL);
		goto parse;
	}
#line 633 "tokenizer.c"
yy62:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yybm[0+yych] & 16) {
			goto yy62;
		}
		switch(yych) {
		case '#':
		case ':':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'H':
		case 'I':
		case 'J':
		case 'L':
		case 'O':
		case 'Q':
		case 'R':
		case 'S':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'h':
		case 'i':
		case 'j':
		case 'l':
		case 'o':
		case 'q':
		case 'r':
		case 's':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy88;
		case 'E':
		case 'e':	goto yy64;
		case 'F':
		case 'f':	goto yy83;
		case 'G':
		case 'g':	goto yy68;
		case 'K':
		case 'k':	goto yy71;
		case 'M':
		case 'm':	goto yy86;
		case 'N':
		case 'n':	goto yy77;
		case 'P':
		case 'p':	goto yy80;
		case 'T':
		case 't':	goto yy65;
		case 'U':
		case 'u':	goto yy74;
		default:	goto yy44;
		}
yy64:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if(yych <= ',') {
			if(yych == '+') goto yy100;
			goto yy89;
		} else {
			if(yych <= '-') goto yy100;
			if(yych <= '/') goto yy89;
			if(yych <= '9') goto yy101;
			goto yy89;
		}
yy65:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yybm[0+yych] & 32) {
			goto yy65;
		}
#line 154 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*1e12, NULL); goto parse; }
#line 719 "tokenizer.c"
yy68:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych >= '#') goto yy68;
			} else {
				if(yych == ':') goto yy68;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy68;
				if(yych >= '_') goto yy68;
			} else {
				if(yych <= '`') goto yy70;
				if(yych <= 'z') goto yy68;
			}
		}
yy70:
#line 155 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*1e9, NULL); goto parse; }
#line 741 "tokenizer.c"
yy71:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych >= '#') goto yy71;
			} else {
				if(yych == ':') goto yy71;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy71;
				if(yych >= '_') goto yy71;
			} else {
				if(yych <= '`') goto yy73;
				if(yych <= 'z') goto yy71;
			}
		}
yy73:
#line 156 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*1e3, NULL); goto parse; }
#line 763 "tokenizer.c"
yy74:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych >= '#') goto yy74;
			} else {
				if(yych == ':') goto yy74;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy74;
				if(yych >= '_') goto yy74;
			} else {
				if(yych <= '`') goto yy76;
				if(yych <= 'z') goto yy74;
			}
		}
yy76:
#line 157 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*1e-6, NULL); goto parse; }
#line 785 "tokenizer.c"
yy77:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych >= '#') goto yy77;
			} else {
				if(yych == ':') goto yy77;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy77;
				if(yych >= '_') goto yy77;
			} else {
				if(yych <= '`') goto yy79;
				if(yych <= 'z') goto yy77;
			}
		}
yy79:
#line 158 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*1e-9, NULL); goto parse; }
#line 807 "tokenizer.c"
yy80:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych >= '#') goto yy80;
			} else {
				if(yych == ':') goto yy80;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy80;
				if(yych >= '_') goto yy80;
			} else {
				if(yych <= '`') goto yy82;
				if(yych <= 'z') goto yy80;
			}
		}
yy82:
#line 159 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*1e-12, NULL); goto parse; }
#line 829 "tokenizer.c"
yy83:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych >= '#') goto yy83;
			} else {
				if(yych == ':') goto yy83;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy83;
				if(yych >= '_') goto yy83;
			} else {
				if(yych <= '`') goto yy85;
				if(yych <= 'z') goto yy83;
			}
		}
yy85:
#line 160 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*1e-15, NULL); goto parse; }
#line 851 "tokenizer.c"
yy86:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= 'I') {
			if(yych == 'E') goto yy92;
			if(yych <= 'H') goto yy91;
			goto yy93;
		} else {
			if(yych <= 'e') {
				if(yych <= 'd') goto yy91;
				goto yy92;
			} else {
				if(yych == 'i') goto yy93;
				goto yy91;
			}
		}
yy87:
#line 163 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*1e-3, NULL); goto parse; }
#line 870 "tokenizer.c"
yy88:
		++YYCURSOR;
		yych = *YYCURSOR;
yy89:
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych <= '"') goto yy44;
				goto yy88;
			} else {
				if(yych == ':') goto yy88;
				goto yy44;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy88;
				if(yych <= '^') goto yy44;
				goto yy88;
			} else {
				if(yych <= '`') goto yy44;
				if(yych <= 'z') goto yy88;
				goto yy44;
			}
		}
yy90:
		++YYCURSOR;
		yych = *YYCURSOR;
yy91:
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych <= '"') goto yy87;
				goto yy90;
			} else {
				if(yych == ':') goto yy90;
				goto yy87;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy90;
				if(yych <= '^') goto yy87;
				goto yy90;
			} else {
				if(yych <= '`') goto yy87;
				if(yych <= 'z') goto yy90;
				goto yy87;
			}
		}
yy92:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy97;
		if(yych == 'g') goto yy97;
		goto yy91;
yy93:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy94;
		if(yych != 'l') goto yy91;
yy94:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych >= '#') goto yy94;
			} else {
				if(yych == ':') goto yy94;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy94;
				if(yych >= '_') goto yy94;
			} else {
				if(yych <= '`') goto yy96;
				if(yych <= 'z') goto yy94;
			}
		}
yy96:
#line 162 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*2.54e-5, NULL); goto parse; }
#line 947 "tokenizer.c"
yy97:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yych <= '?') {
			if(yych <= '#') {
				if(yych >= '#') goto yy97;
			} else {
				if(yych == ':') goto yy97;
			}
		} else {
			if(yych <= '_') {
				if(yych <= 'Z') goto yy97;
				if(yych >= '_') goto yy97;
			} else {
				if(yych <= '`') goto yy99;
				if(yych <= 'z') goto yy97;
			}
		}
yy99:
#line 161 "tokenizer.re"
		{ Attach(TOKEN_CONSTANT, NULL, atof(start)*1e6, NULL); goto parse; }
#line 969 "tokenizer.c"
yy100:
		yych = *++YYCURSOR;
		if(yych <= '/') goto yy52;
		if(yych >= ':') goto yy52;
yy101:
		++YYCURSOR;
		yych = *YYCURSOR;
		switch(yych) {
		case '#':
		case ':':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'H':
		case 'I':
		case 'J':
		case 'L':
		case 'O':
		case 'Q':
		case 'R':
		case 'S':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'h':
		case 'i':
		case 'j':
		case 'l':
		case 'o':
		case 'q':
		case 'r':
		case 's':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy88;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy101;
		case 'F':
		case 'f':	goto yy83;
		case 'G':
		case 'g':	goto yy68;
		case 'K':
		case 'k':	goto yy71;
		case 'M':
		case 'm':	goto yy86;
		case 'N':
		case 'n':	goto yy77;
		case 'P':
		case 'p':	goto yy80;
		case 'T':
		case 't':	goto yy65;
		case 'U':
		case 'u':	goto yy74;
		default:	goto yy44;
		}
yy103:
		yych = *++YYCURSOR;
		if(yych <= '/') goto yy52;
		if(yych <= '9') goto yy106;
		goto yy52;
yy104:
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		switch(yych) {
		case '#':
		case ':':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'H':
		case 'I':
		case 'J':
		case 'L':
		case 'O':
		case 'Q':
		case 'R':
		case 'S':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'h':
		case 'i':
		case 'j':
		case 'l':
		case 'o':
		case 'q':
		case 'r':
		case 's':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy88;
		case '.':	goto yy103;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy104;
		case 'E':
		case 'e':	goto yy64;
		case 'F':
		case 'f':	goto yy83;
		case 'G':
		case 'g':	goto yy68;
		case 'K':
		case 'k':	goto yy71;
		case 'M':
		case 'm':	goto yy86;
		case 'N':
		case 'n':	goto yy77;
		case 'P':
		case 'p':	goto yy80;
		case 'T':
		case 't':	goto yy65;
		case 'U':
		case 'u':	goto yy74;
		default:	goto yy44;
		}
yy106:
		++YYCURSOR;
		yych = *YYCURSOR;
		switch(yych) {
		case '#':
		case ':':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'H':
		case 'I':
		case 'J':
		case 'L':
		case 'O':
		case 'Q':
		case 'R':
		case 'S':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'h':
		case 'i':
		case 'j':
		case 'l':
		case 'o':
		case 'q':
		case 'r':
		case 's':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy88;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy106;
		case 'E':
		case 'e':	goto yy64;
		case 'F':
		case 'f':	goto yy83;
		case 'G':
		case 'g':	goto yy68;
		case 'K':
		case 'k':	goto yy71;
		case 'M':
		case 'm':	goto yy86;
		case 'N':
		case 'n':	goto yy77;
		case 'P':
		case 'p':	goto yy80;
		case 'T':
		case 't':	goto yy65;
		case 'U':
		case 'u':	goto yy74;
		default:	goto yy44;
		}
yy108:
		yych = *++YYCURSOR;
		if(yych == '(') goto yy112;
		goto yy50;
yy109:
		yych = *++YYCURSOR;
		if(yych == ')') goto yy52;
		goto yy111;
yy110:
		++YYCURSOR;
		yych = *YYCURSOR;
yy111:
		if(yych <= ':') {
			if(yych <= '(') {
				if(yych == '#') goto yy110;
				goto yy52;
			} else {
				if(yych <= ')') goto yy55;
				if(yych <= '/') goto yy52;
				goto yy110;
			}
		} else {
			if(yych <= '^') {
				if(yych <= '?') goto yy52;
				if(yych <= 'Z') goto yy110;
				goto yy52;
			} else {
				if(yych == '`') goto yy52;
				if(yych <= 'z') goto yy110;
				goto yy52;
			}
		}
yy112:
		++YYCURSOR;
#line 140 "tokenizer.re"
		{ Attach(TOKEN_IF, NULL, 0, minDiv);		goto parse; }
#line 1233 "tokenizer.c"
yy114:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy117;
		if(yych == 'a') goto yy117;
		goto yy50;
yy115:
		++YYCURSOR;
#line 139 "tokenizer.re"
		{ Attach(TOKEN_U, NULL, 0, minDiv);		goto parse; }
#line 1243 "tokenizer.c"
yy117:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy118;
		if(yych != 'm') goto yy50;
yy118:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy119;
		if(yych != 'p') goto yy50;
yy119:
		yych = *++YYCURSOR;
		if(yych != '(') goto yy50;
		++YYCURSOR;
#line 138 "tokenizer.re"
		{ Attach(TOKEN_URAMP, NULL, 0, minDiv);	goto parse; }
#line 1258 "tokenizer.c"
yy122:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy123;
		if(yych != 'n') goto yy50;
yy123:
		yych = *++YYCURSOR;
		if(yych != '(') goto yy50;
		++YYCURSOR;
#line 137 "tokenizer.re"
		{ Attach(TOKEN_TAN, NULL, 0, minDiv);		goto parse; }
#line 1269 "tokenizer.c"
yy126:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy132;
		if(yych == 'n') goto yy132;
		goto yy50;
yy127:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy128;
		if(yych != 'r') goto yy50;
yy128:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy129;
		if(yych != 't') goto yy50;
yy129:
		yych = *++YYCURSOR;
		if(yych != '(') goto yy50;
		++YYCURSOR;
#line 136 "tokenizer.re"
		{ Attach(TOKEN_SQRT, NULL, 0, minDiv);		goto parse; }
#line 1289 "tokenizer.c"
yy132:
		yych = *++YYCURSOR;
		if(yych <= 'G') {
			if(yych == '(') goto yy134;
			goto yy50;
		} else {
			if(yych <= 'H') goto yy133;
			if(yych != 'h') goto yy50;
		}
yy133:
		yych = *++YYCURSOR;
		if(yych == '(') goto yy136;
		goto yy50;
yy134:
		++YYCURSOR;
#line 135 "tokenizer.re"
		{ Attach(TOKEN_SIN, NULL, 0, minDiv);		goto parse; }
#line 1307 "tokenizer.c"
yy136:
		++YYCURSOR;
#line 134 "tokenizer.re"
		{ Attach(TOKEN_SINH, NULL, 0, minDiv);		goto parse; }
#line 1312 "tokenizer.c"
yy138:
		yych = *++YYCURSOR;
		if(yych == '(') goto yy143;
		goto yy50;
yy139:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy140;
		if(yych != 'g') goto yy50;
yy140:
		yych = *++YYCURSOR;
		if(yych != '(') goto yy50;
		++YYCURSOR;
#line 133 "tokenizer.re"
		{ Attach(TOKEN_LOG, NULL, 0, minDiv);		goto parse; }
#line 1327 "tokenizer.c"
yy143:
		++YYCURSOR;
#line 132 "tokenizer.re"
		{ Attach(TOKEN_LN, NULL, 0, minDiv);		goto parse; }
#line 1332 "tokenizer.c"
yy145:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy146;
		if(yych != 'p') goto yy50;
yy146:
		yych = *++YYCURSOR;
		if(yych != '(') goto yy50;
		++YYCURSOR;
#line 131 "tokenizer.re"
		{ Attach(TOKEN_EXP, NULL, 0, minDiv);		goto parse; }
#line 1343 "tokenizer.c"
yy149:
		yych = *++YYCURSOR;
		if(yych == 'S') goto yy150;
		if(yych != 's') goto yy50;
yy150:
		yych = *++YYCURSOR;
		if(yych <= 'G') {
			if(yych == '(') goto yy152;
			goto yy50;
		} else {
			if(yych <= 'H') goto yy151;
			if(yych != 'h') goto yy50;
		}
yy151:
		yych = *++YYCURSOR;
		if(yych == '(') goto yy154;
		goto yy50;
yy152:
		++YYCURSOR;
#line 130 "tokenizer.re"
		{ Attach(TOKEN_COS, NULL, 0, minDiv);		goto parse; }
#line 1365 "tokenizer.c"
yy154:
		++YYCURSOR;
#line 129 "tokenizer.re"
		{ Attach(TOKEN_COSH, NULL, 0, minDiv);		goto parse; }
#line 1370 "tokenizer.c"
yy156:
		yych = *++YYCURSOR;
		if(yych == 'S') goto yy181;
		if(yych == 's') goto yy181;
		goto yy50;
yy157:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy174;
		if(yych == 'o') goto yy174;
		goto yy50;
yy158:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy167;
		if(yych == 'i') goto yy167;
		goto yy50;
yy159:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy160;
		if(yych != 'a') goto yy50;
yy160:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy161;
		if(yych != 'n') goto yy50;
yy161:
		yych = *++YYCURSOR;
		if(yych <= 'G') {
			if(yych == '(') goto yy163;
			goto yy50;
		} else {
			if(yych <= 'H') goto yy162;
			if(yych != 'h') goto yy50;
		}
yy162:
		yych = *++YYCURSOR;
		if(yych == '(') goto yy165;
		goto yy50;
yy163:
		++YYCURSOR;
#line 128 "tokenizer.re"
		{ Attach(TOKEN_ATAN, NULL, 0, minDiv);		goto parse; }
#line 1411 "tokenizer.c"
yy165:
		++YYCURSOR;
#line 127 "tokenizer.re"
		{ Attach(TOKEN_ATANH, NULL, 0, minDiv);	goto parse; }
#line 1416 "tokenizer.c"
yy167:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy168;
		if(yych != 'n') goto yy50;
yy168:
		yych = *++YYCURSOR;
		if(yych <= 'G') {
			if(yych == '(') goto yy170;
			goto yy50;
		} else {
			if(yych <= 'H') goto yy169;
			if(yych != 'h') goto yy50;
		}
yy169:
		yych = *++YYCURSOR;
		if(yych == '(') goto yy172;
		goto yy50;
yy170:
		++YYCURSOR;
#line 126 "tokenizer.re"
		{ Attach(TOKEN_ASIN, NULL, 0, minDiv);		goto parse; }
#line 1438 "tokenizer.c"
yy172:
		++YYCURSOR;
#line 125 "tokenizer.re"
		{ Attach(TOKEN_ASINH, NULL, 0, minDiv);	goto parse; }
#line 1443 "tokenizer.c"
yy174:
		yych = *++YYCURSOR;
		if(yych == 'S') goto yy175;
		if(yych != 's') goto yy50;
yy175:
		yych = *++YYCURSOR;
		if(yych <= 'G') {
			if(yych == '(') goto yy177;
			goto yy50;
		} else {
			if(yych <= 'H') goto yy176;
			if(yych != 'h') goto yy50;
		}
yy176:
		yych = *++YYCURSOR;
		if(yych == '(') goto yy179;
		goto yy50;
yy177:
		++YYCURSOR;
#line 124 "tokenizer.re"
		{ Attach(TOKEN_ACOS, NULL, 0, minDiv);		goto parse; }
#line 1465 "tokenizer.c"
yy179:
		++YYCURSOR;
#line 123 "tokenizer.re"
		{ Attach(TOKEN_ACOSH, NULL, 0, minDiv);	goto parse; }
#line 1470 "tokenizer.c"
yy181:
		yych = *++YYCURSOR;
		if(yych != '(') goto yy50;
		++YYCURSOR;
#line 122 "tokenizer.re"
		{ Attach(TOKEN_ABS, NULL, 0, minDiv);		goto parse; }
#line 1477 "tokenizer.c"
yy184:
		yych = *++YYCURSOR;
		goto yy3;
yy185:
		++YYCURSOR;
		yych = *YYCURSOR;
		if(yybm[0+yych] & 64) {
			goto yy185;
		}
		if(yych == '+') goto yy184;
		goto yy52;
yy187:
		++YYCURSOR;
		yych = *YYCURSOR;
yy188:
		if(yybm[0+yych] & 128) {
			goto yy187;
		}
		goto yy3;
	}
}
#line 242 "tokenizer.re"


passed:
	return tokens;
failed:
	if(tokens != NULL) {
		if(listDestroy(&tokens, (listDestroy_)tokenDestroy)) {
			Warn("Failed to destroy token list");
		}
	}
	return NULL;
}
